"""Regression for admin activity usage reporting."""
from datetime import date, datetime, timezone
from pathlib import Path
import csv, io, sys, uuid
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from fastapi.testclient import TestClient

from app.core.database import SessionLocal
from app.main import app
from app.modules.farmer.models import Farmer, Parcel, Project, Tenant
from app.modules.master_data.models import AgriculturalInput, AgriculturalProduct, AgriculturalProductPackage, CropStageInputRule, Manufacturer, ProjectProductApproval
from app.modules.workflow.models import CropActivity, CropCycle, CropStageInstance, WorkflowTemplate, WorkflowTemplateVersion
from scripts.admin_auth_test_utils import create_test_admin, delete_test_admin

TENANT = "default"
MFG = "REPORT_USAGE_AGRO"
PRODUCT = "REPORT_USAGE_UREA"
SKU = "REPORT_USAGE_UREA_45KG"


def now(): return datetime.now(timezone.utc)

def check(value, label, detail=None):
    if not value: raise AssertionError(f"{label}: {detail or ''}")
    print("  OK", label)


def cleanup(db, *, admin=None, farmer_id, parcel_id, project_id, cycle_id=None):
    db.rollback()
    if cycle_id:
        db.query(CropActivity).filter(CropActivity.crop_cycle_id == cycle_id).delete(synchronize_session=False)
        db.query(CropStageInstance).filter(CropStageInstance.crop_cycle_id == cycle_id).delete(synchronize_session=False)
        db.query(CropCycle).filter(CropCycle.id == cycle_id).delete(synchronize_session=False)
    db.query(CropStageInputRule).filter(CropStageInputRule.project_id == project_id).delete(synchronize_session=False)
    product = db.query(AgriculturalProduct).filter(AgriculturalProduct.code == PRODUCT).first()
    if product:
        db.query(ProjectProductApproval).filter(ProjectProductApproval.product_id == product.id).delete(synchronize_session=False)
        db.query(AgriculturalProductPackage).filter(AgriculturalProductPackage.product_id == product.id).delete(synchronize_session=False)
        db.query(AgriculturalProduct).filter(AgriculturalProduct.id == product.id).delete(synchronize_session=False)
    db.query(Manufacturer).filter(Manufacturer.code == MFG).delete(synchronize_session=False)
    db.query(Parcel).filter(Parcel.id == parcel_id).delete(synchronize_session=False)
    db.query(Farmer).filter(Farmer.id == farmer_id).delete(synchronize_session=False)
    db.query(Project).filter(Project.id == project_id).delete(synchronize_session=False)
    db.commit()
    if admin: delete_test_admin(db, admin.id)


def main():
    print("=" * 72)
    print("ACTIVITY USAGE REPORT REGRESSION")
    print("=" * 72)
    db = SessionLocal(); admin, headers = create_test_admin(db)
    farmer_id, parcel_id, project_id, cycle_id = uuid.uuid4(), uuid.uuid4(), uuid.uuid4(), None
    try:
        if not db.query(Tenant).filter(Tenant.id == TENANT).first(): db.add(Tenant(id=TENANT, name="Default", type="ENTERPRISE", created_at=now(), updated_at=now()))
        urea = db.query(AgriculturalInput).filter(AgriculturalInput.code == "UREA_46_N", AgriculturalInput.catalog_status == "PUBLISHED", AgriculturalInput.is_active == True).first(); check(urea is not None, "Urea input exists")
        workflow_template = db.query(WorkflowTemplate).filter(WorkflowTemplate.code == "WF_RICE_KHARIF_DEFAULT").first(); check(workflow_template is not None, "Rice workflow template exists")
        workflow_version = db.query(WorkflowTemplateVersion).filter(WorkflowTemplateVersion.template_id == workflow_template.id, WorkflowTemplateVersion.status == "PUBLISHED", WorkflowTemplateVersion.is_active == True).first(); check(workflow_version is not None, "Rice workflow version exists")
        project = Project(id=project_id, tenant_id=TENANT, name="Usage Report Project", start_date=date(2027,1,1), end_date=date(2027,12,31), status="PLANNED", crop_scope=["RICE"], created_at=now(), updated_at=now())
        farmer = Farmer(id=farmer_id, tenant_id=TENANT, project_id=project_id, mobile_number="996" + str(farmer_id.int)[-7:], village_name_manual="Report Village", primary_crop_code="RICE", display_name="Report Farmer", status="ACTIVE", created_at=now(), updated_at=now())
        parcel = Parcel(id=parcel_id, tenant_id=TENANT, farmer_id=farmer_id, project_id=project_id, village_name_manual="Report Village", reported_area=1, reported_area_unit="ACRE", survey_number="REPORT-" + str(parcel_id)[:8], ownership_type="OWNED", status="ACTIVE", created_at=now(), updated_at=now())
        db.add(project); db.flush(); db.add_all([farmer, parcel]); db.flush()
        mfg = Manufacturer(id=uuid.uuid4(), code=MFG, canonical_name="Report Usage Agro", country="India", aliases=[], created_at=now(), updated_at=now()); db.add(mfg); db.flush()
        product = AgriculturalProduct(id=uuid.uuid4(), code=PRODUCT, canonical_input_id=urea.id, manufacturer_id=mfg.id, brand_name="Report Usage Urea", composition="46% N", registration_number="REPORT-USAGE-UREA-001", country="India", status="ACTIVE", created_at=now(), updated_at=now()); db.add(product); db.flush()
        package = AgriculturalProductPackage(id=uuid.uuid4(), product_id=product.id, sku=SKU, quantity="45", unit="kg", pack_label="45 kg bag", status="ACTIVE", created_at=now(), updated_at=now())
        approval = ProjectProductApproval(id=uuid.uuid4(), tenant_id=TENANT, project_id=project_id, product_id=product.id, enabled=True, preferred=True, display_order=1, reason="Usage report test", created_at=now(), updated_at=now())
        rule = CropStageInputRule(id=uuid.uuid4(), tenant_id=TENANT, project_id=project_id, crop_code="RICE", season_code="KHARIF", stage_code="TILLERING", activity_type="FERTILIZER", input_id=urea.id, input_code="UREA_46_N", enabled=True, priority=1, dosage_quantity="36", dosage_unit="KG", dosage_area_unit="ACRE", allowed_product_codes=[PRODUCT], reason="Usage report rule", created_at=now(), updated_at=now())
        cycle_id = uuid.uuid4()
        cycle = CropCycle(id=cycle_id, tenant_id=TENANT, farmer_id=farmer_id, parcel_id=parcel_id, project_id=project_id, crop_code="RICE", season_code="KHARIF", lifecycle_template_id=workflow_template.lifecycle_template_id, workflow_template_version_id=workflow_version.id, planned_sowing_date=date(2027,6,15), status="ACTIVE", created_at=now(), updated_at=now())
        stage = CropStageInstance(id=uuid.uuid4(), crop_cycle_id=cycle_id, tenant_id=TENANT, stage_code="TILLERING", stage_name="Tillering", stage_order=3, expected_duration_days=30, status="ACTIVE", created_at=now(), updated_at=now())
        activity = CropActivity(id=uuid.uuid4(), crop_cycle_id=cycle_id, stage_instance_id=stage.id, tenant_id=TENANT, farmer_id=farmer_id, activity_type="FERTILIZER", input_code="UREA_46_N", input_name="Urea", quantity="38", quantity_unit="KG", input_rule_id=rule.id, product_id=product.id, product_code=PRODUCT, package_id=package.id, package_sku=SKU, recommended_quantity="36", recommended_quantity_unit="KG", actual_quantity="38", actual_quantity_unit="KG", dosage_variance_reason="Field adjustment", cost_amount="1200", activity_date=date(2027,7,20), logged_by=admin.id, created_at=now(), updated_at=now())
        db.add_all([package, approval, rule, cycle, stage, activity]); db.commit()

        client = TestClient(app, headers=headers)
        response = client.get(f"/api/v1/reports/activity-usage?project_id={project_id}&crop_code=RICE&stage_code=TILLERING&product_code={PRODUCT}")
        check(response.status_code == 200, "activity usage report returns 200", response.text[:300])
        payload = response.json(); check(payload["count"] == 1, "report returns one row")
        row = payload["activities"][0]
        check(row["activity_id"] == str(activity.id), "report row includes activity id")
        check(row["product_code"] == PRODUCT and row["package_sku"] == SKU, "report row includes product/package")
        check(row["stage_instance_id"] == str(stage.id) and row["stage_status"] == "ACTIVE", "report row includes stage traceability")
        check(row["crop_cycle_status"] == "ACTIVE" and row["workflow_template_version_id"] == str(workflow_version.id), "report row includes cycle traceability")
        check(row["logged_by"] == str(admin.id) and row["logging_method"] == "MANUAL", "report row includes logging traceability")
        check(row["recommended_quantity"] == "36.000" and row["actual_quantity"] == "38.000", "report row includes quantities")
        check(payload["summary"]["activity_count"] == 1, "summary activity count is correct")
        check(payload["summary"]["total_cost"] == "1200.00", "summary total cost is correct")
        check(payload["summary"]["variance_count"] == 1, "summary variance count is correct")
        check(payload["summary"]["quantity_by_input"][0]["quantity"] == "38.000", "summary quantity by input is correct")
        check(payload["summary"]["quantity_by_product"][0]["product_code"] == PRODUCT, "summary quantity by product is correct")

        csv_response = client.get(f"/api/v1/reports/activity-usage.csv?project_id={project_id}&crop_code=RICE&stage_code=TILLERING&product_code={PRODUCT}")
        check(csv_response.status_code == 200, "activity usage CSV returns 200", csv_response.text[:300])
        check(csv_response.headers["content-type"].startswith("text/csv"), "CSV content type is text/csv")
        check("activity_usage.csv" in csv_response.headers.get("content-disposition", ""), "CSV response has download filename")
        csv_rows = list(csv.DictReader(io.StringIO(csv_response.text)))
        check(len(csv_rows) == 1, "CSV export returns one row")
        check(csv_rows[0]["activity_id"] == str(activity.id), "CSV row includes activity id")
        check(csv_rows[0]["product_code"] == PRODUCT and csv_rows[0]["package_sku"] == SKU, "CSV row includes product/package")
        check(csv_rows[0]["stage_instance_id"] == str(stage.id), "CSV row includes stage instance id")
        check(csv_rows[0]["workflow_template_version_id"] == str(workflow_version.id), "CSV row includes workflow version id")
        check(csv_rows[0]["actual_quantity"] == "38.000", "CSV row includes actual quantity")

        options_response = client.get("/api/v1/reports/activity-usage/filter-options")
        check(options_response.status_code == 200, "activity usage filter options return 200", options_response.text[:300])
        options = options_response.json()
        check(any(item["id"] == str(project_id) for item in options["projects"]), "filter options include project")
        check("RICE" in options["crops"] and "KHARIF" in options["seasons"], "filter options include crop and season")
        check(any(item["code"] == "TILLERING" for item in options["stages"]), "filter options include stage")
        check(any(item["code"] == "UREA_46_N" for item in options["inputs"]), "filter options include input")
        check(any(item["code"] == PRODUCT for item in options["products"]), "filter options include product")
        trace_response = client.get(f"/api/v1/reports/crop-cycles/{cycle_id}/trace")
        check(trace_response.status_code == 200, "crop cycle trace returns 200", trace_response.text[:300])
        trace = trace_response.json()
        check(trace["cycle"]["id"] == str(cycle_id), "trace includes cycle")
        check(trace["farmer"]["id"] == str(farmer_id) and trace["parcel"]["id"] == str(parcel_id), "trace includes farmer and parcel")
        check(trace["summary"]["activity_count"] == 1 and trace["summary"]["total_cost"] == "1200.00", "trace summary is correct")
        check(trace["stages"][0]["stage_code"] == "TILLERING" and trace["stages"][0]["activity_count"] == 1, "trace includes stage activity counts")
        check(trace["activities"][0]["activity_id"] == str(activity.id), "trace includes activity row")
        check(trace["activities"][0]["workflow_template_version_id"] == str(workflow_version.id), "trace activity includes workflow version")
        rule_trace_response = client.get(f"/api/v1/reports/input-rules/{rule.id}/trace")
        check(rule_trace_response.status_code == 200, "input rule trace returns 200", rule_trace_response.text[:300])
        rule_trace = rule_trace_response.json()
        check(rule_trace["rule"]["id"] == str(rule.id), "rule trace includes rule")
        check(rule_trace["input"]["code"] == "UREA_46_N", "rule trace includes canonical input")
        check(rule_trace["products"][0]["code"] == PRODUCT, "rule trace includes allowed product")
        check(rule_trace["products"][0]["approval"]["enabled"] is True, "rule trace includes product approval")
        check(rule_trace["summary"]["activity_count"] == 1 and rule_trace["summary"]["variance_count"] == 1, "rule trace summary is correct")
        check(rule_trace["activities"][0]["activity_id"] == str(activity.id), "rule trace includes activity")
        product_trace_response = client.get(f"/api/v1/reports/products/{PRODUCT}/trace")
        check(product_trace_response.status_code == 200, "product trace returns 200", product_trace_response.text[:300])
        product_trace = product_trace_response.json()
        check(product_trace["product"]["code"] == PRODUCT, "product trace includes product")
        check(product_trace["input"]["code"] == "UREA_46_N", "product trace includes canonical input")
        check(product_trace["packages"][0]["sku"] == SKU and product_trace["packages"][0]["activity_count"] == 1, "product trace includes package usage")
        check(product_trace["project_approvals"][0]["enabled"] is True, "product trace includes project approval")
        check(product_trace["input_rules"][0]["id"] == str(rule.id), "product trace includes allowing input rule")
        check(product_trace["summary"]["activity_count"] == 1 and product_trace["summary"]["quantity_by_package"][0]["package_sku"] == SKU, "product trace summary is correct")
        check(product_trace["activities"][0]["activity_id"] == str(activity.id), "product trace includes activity")
        project_trace_response = client.get(f"/api/v1/reports/projects/{project_id}/trace")
        check(project_trace_response.status_code == 200, "project trace returns 200", project_trace_response.text[:300])
        project_trace = project_trace_response.json()
        check(project_trace["project"]["id"] == str(project_id), "project trace includes project")
        check(project_trace["summary"]["farmer_count"] == 1 and project_trace["summary"]["parcel_count"] == 1, "project trace farmer/parcel counts are correct")
        check(project_trace["summary"]["crop_cycle_count"] == 1 and project_trace["summary"]["activity_count"] == 1, "project trace cycle/activity counts are correct")
        check(project_trace["summary"]["total_cost"] == "1200.00" and project_trace["summary"]["variance_count"] == 1, "project trace summary totals are correct")
        check(project_trace["crop_distribution"][0]["crop_code"] == "RICE", "project trace crop distribution is correct")
        check(project_trace["farmers"][0]["trace_url"] == f"/farmer-trace/{farmer_id}", "project trace farmer link is correct")
        check(project_trace["parcels"][0]["trace_url"] == f"/parcel-trace/{parcel_id}", "project trace parcel link is correct")
        check(project_trace["crop_cycles"][0]["id"] == str(cycle_id), "project trace includes crop cycle")
        check(project_trace["activities"][0]["activity_id"] == str(activity.id), "project trace includes activity row")
        filtered_trace_response = client.get(f"/api/v1/reports/projects/{project_id}/trace?crop_code=RICE&activity_type=FERTILIZER&has_variance=true")
        check(filtered_trace_response.status_code == 200, "filtered project trace returns 200", filtered_trace_response.text[:300])
        filtered_trace = filtered_trace_response.json()
        check(filtered_trace["filters"]["crop_code"] == "RICE" and filtered_trace["filters"]["has_variance"] is True, "filtered project trace echoes filters")
        check(filtered_trace["summary"]["activity_count"] == 1 and filtered_trace["activities"][0]["activity_id"] == str(activity.id), "filtered project trace returns matching activity")
        wrong_crop_trace = client.get(f"/api/v1/reports/projects/{project_id}/trace?crop_code=WHEAT").json()
        check(wrong_crop_trace["summary"]["activity_count"] == 0 and wrong_crop_trace["activities"] == [], "project trace wrong crop filter returns no activities")
        project_trace_csv_response = client.get(f"/api/v1/reports/projects/{project_id}/trace.csv")
        check(project_trace_csv_response.status_code == 200, "project trace CSV returns 200", project_trace_csv_response.text[:300])
        check(project_trace_csv_response.headers["content-type"].startswith("text/csv"), "project trace CSV content type is text/csv")
        check("project_trace_" in project_trace_csv_response.headers.get("content-disposition", ""), "project trace CSV response has filename")
        project_trace_csv_rows = list(csv.DictReader(io.StringIO(project_trace_csv_response.text)))
        check(len(project_trace_csv_rows) == 1, "project trace CSV returns one activity row")
        check(project_trace_csv_rows[0]["project_id"] == str(project_id) and project_trace_csv_rows[0]["activity_id"] == str(activity.id), "project trace CSV includes project and activity ids")
        check(project_trace_csv_rows[0]["product_code"] == PRODUCT and project_trace_csv_rows[0]["package_sku"] == SKU, "project trace CSV includes product/package")
        filtered_csv_response = client.get(f"/api/v1/reports/projects/{project_id}/trace.csv?crop_code=WHEAT")
        check(filtered_csv_response.status_code == 200, "filtered project trace CSV returns 200", filtered_csv_response.text[:300])
        check(len(list(csv.DictReader(io.StringIO(filtered_csv_response.text)))) == 0, "project trace CSV respects wrong crop filter")
        variance_csv_response = client.get(f"/api/v1/reports/projects/{project_id}/trace.csv?has_variance=true")
        variance_csv_rows = list(csv.DictReader(io.StringIO(variance_csv_response.text)))
        check(len(variance_csv_rows) == 1 and variance_csv_rows[0]["activity_id"] == str(activity.id), "project trace CSV respects variance filter")
        compliance_response = client.get(f"/api/v1/reports/projects/{project_id}/input-compliance")
        check(compliance_response.status_code == 200, "project input compliance returns 200", compliance_response.text[:300])
        compliance = compliance_response.json()
        check(compliance["project"]["id"] == str(project_id), "compliance includes project")
        check(compliance["summary"]["activity_count"] == 1, "compliance summary includes activity count")
        check(compliance["summary"]["recommendation_linked_count"] == 1 and compliance["summary"]["custom_activity_count"] == 0, "compliance linked/custom counts are correct")
        check(compliance["summary"]["product_approved_count"] == 1 and compliance["summary"]["product_unapproved_count"] == 0, "compliance product approval counts are correct")
        check(compliance["summary"]["variance_count"] == 1 and compliance["top_variance_reasons"][0]["reason"] == "Field adjustment", "compliance variance summary is correct")
        check(compliance["quantity_by_input"][0]["input_code"] == "UREA_46_N", "compliance quantity by input is correct")
        check(compliance["activity_count_by_crop_stage"][0]["stage_code"] == "TILLERING", "compliance crop-stage count is correct")
        farmer_trace_response = client.get(f"/api/v1/reports/farmers/{farmer_id}/trace")
        check(farmer_trace_response.status_code == 200, "farmer trace returns 200", farmer_trace_response.text[:300])
        farmer_trace = farmer_trace_response.json()
        check(farmer_trace["farmer"]["id"] == str(farmer_id), "farmer trace includes farmer")
        check(farmer_trace["project"]["id"] == str(project_id), "farmer trace includes project")
        check(farmer_trace["summary"]["parcel_count"] == 1, "farmer trace parcel count is correct")
        check(farmer_trace["summary"]["crop_cycle_count"] == 1 and farmer_trace["summary"]["activity_count"] == 1, "farmer trace cycle/activity counts are correct")
        check(farmer_trace["summary"]["total_cost"] == "1200.00" and farmer_trace["summary"]["variance_count"] == 1, "farmer trace summary totals are correct")
        check(farmer_trace["parcels"][0]["id"] == str(parcel_id) and farmer_trace["parcels"][0]["activity_count"] == 1, "farmer trace includes parcel usage")
        check(farmer_trace["crop_cycles"][0]["id"] == str(cycle_id) and farmer_trace["crop_cycles"][0]["workflow_template_version_id"] == str(workflow_version.id), "farmer trace includes cycle usage")
        check(farmer_trace["activities"][0]["activity_id"] == str(activity.id), "farmer trace includes activity row")
        parcel_trace_response = client.get(f"/api/v1/reports/parcels/{parcel_id}/trace")
        check(parcel_trace_response.status_code == 200, "parcel trace returns 200", parcel_trace_response.text[:300])
        parcel_trace = parcel_trace_response.json()
        check(parcel_trace["parcel"]["id"] == str(parcel_id), "parcel trace includes parcel")
        check(parcel_trace["farmer"]["id"] == str(farmer_id), "parcel trace includes farmer")
        check(parcel_trace["project"]["id"] == str(project_id), "parcel trace includes project")
        check(parcel_trace["summary"]["crop_cycle_count"] == 1 and parcel_trace["summary"]["activity_count"] == 1, "parcel trace cycle/activity counts are correct")
        check(parcel_trace["summary"]["total_cost"] == "1200.00" and parcel_trace["summary"]["variance_count"] == 1, "parcel trace summary totals are correct")
        check(parcel_trace["crop_cycles"][0]["id"] == str(cycle_id), "parcel trace includes cycle")
        check(parcel_trace["activities"][0]["activity_id"] == str(activity.id), "parcel trace includes activity row")
        lookup_response = client.get("/api/v1/reports/lookup?q=Usage%20Report")
        check(lookup_response.status_code == 200, "admin lookup returns 200", lookup_response.text[:300])
        lookup = lookup_response.json()
        check(any(item["id"] == str(project_id) and item["trace_url"] == f"/project-trace/{project_id}" and item["compliance_url"] == f"/project-compliance/{project_id}" for item in lookup["projects"]), "lookup finds project by name with trace/compliance URLs")
        lookup_csv_response = client.get("/api/v1/reports/lookup.csv?q=Report")
        check(lookup_csv_response.status_code == 200, "admin lookup CSV returns 200", lookup_csv_response.text[:300])
        check(lookup_csv_response.headers["content-type"].startswith("text/csv"), "admin lookup CSV content type is text/csv")
        lookup_csv_rows = list(csv.DictReader(io.StringIO(lookup_csv_response.text)))
        check(any(row["entity_type"] == "PROJECT" and row["id"] == str(project_id) and row["trace_url"] == f"/project-trace/{project_id}" for row in lookup_csv_rows), "lookup CSV includes project trace row")
        check(any(row["entity_type"] == "FARMER" and row["id"] == str(farmer_id) for row in lookup_csv_rows), "lookup CSV includes farmer row")
        check(any(row["entity_type"] == "PARCEL" and row["id"] == str(parcel_id) for row in lookup_csv_rows), "lookup CSV includes parcel row")
        farmer_lookup = client.get(f"/api/v1/reports/lookup?q={farmer.mobile_number}").json()
        check(any(item["id"] == str(farmer_id) and item["trace_url"] == f"/farmer-trace/{farmer_id}" for item in farmer_lookup["farmers"]), "lookup finds farmer by mobile with trace URL")
        parcel_lookup = client.get(f"/api/v1/reports/lookup?q={parcel.survey_number}").json()
        check(any(item["id"] == str(parcel_id) and item["trace_url"] == f"/parcel-trace/{parcel_id}" for item in parcel_lookup["parcels"]), "lookup finds parcel by survey with trace URL")
        parcel_uuid_lookup = client.get(f"/api/v1/reports/lookup?q={parcel_id}").json()
        check(any(item["id"] == str(parcel_id) for item in parcel_uuid_lookup["parcels"]), "lookup finds parcel by UUID")
        print("PASS")
    finally:
        cleanup(db, admin=admin, farmer_id=farmer_id, parcel_id=parcel_id, project_id=project_id, cycle_id=cycle_id)
        db.close()

if __name__ == "__main__": main()
