"use client";
import { useEffect, useState } from "react";
import { productCatalogApi, type AgriculturalProductDto, type ManufacturerDto } from "@/lib/api";

export default function ProductsPage(){
 const [manufacturers,setManufacturers]=useState<ManufacturerDto[]>([]),[products,setProducts]=useState<AgriculturalProductDto[]>([]);
 const [error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const [mfg,setMfg]=useState({code:"",canonical_name:"",short_name:"",country:"India",reason:"Created in admin"});
 const [product,setProduct]=useState({code:"",canonical_input_code:"",manufacturer_code:"",brand_name:"",composition:"",registration_number:"",registration_authority:"",sku:"",quantity:"",unit:"kg",pack_label:"",barcode:"",reason:"Created in admin"});
 const [approval,setApproval]=useState({project_id:"",product_code:"",enabled:true,preferred:false,display_order:"1000",reason:"Project product approval"});
 const load=async()=>{try{const [m,p]=await Promise.all([productCatalogApi.manufacturers(),productCatalogApi.products({includeInactive:true})]);setManufacturers(m.manufacturers);setProducts(p.products)}catch(e){setError(e instanceof Error?e.message:"Load failed")}};
 useEffect(()=>{void load()},[]);
 const createMfg=async()=>{setBusy(true);setError("");try{await productCatalogApi.createManufacturer({...mfg,aliases:[]});setMfg({...mfg,code:"",canonical_name:"",short_name:""});setNotice("Manufacturer created");await load()}catch(e){setError(e instanceof Error?e.message:"Create failed")}finally{setBusy(false)}};
 const createProduct=async()=>{setBusy(true);setError("");try{await productCatalogApi.createProduct({code:product.code,canonical_input_code:product.canonical_input_code,manufacturer_code:product.manufacturer_code,brand_name:product.brand_name,composition:product.composition||null,registration_number:product.registration_number||null,registration_authority:product.registration_authority||null,country:"India",packages:[{sku:product.sku,quantity:product.quantity,unit:product.unit,pack_label:product.pack_label,barcode:product.barcode||null}],reason:product.reason});setNotice("Product and package created");await load()}catch(e){setError(e instanceof Error?e.message:"Create failed")}finally{setBusy(false)}};
 const approve=async()=>{setBusy(true);setError("");try{await productCatalogApi.approveProduct(approval.project_id,approval.product_code,{enabled:approval.enabled,preferred:approval.preferred,display_order:Number(approval.display_order),reason:approval.reason});setNotice("Project approval saved")}catch(e){setError(e instanceof Error?e.message:"Approval failed")}finally{setBusy(false)}};
 return <div><h1 className="text-2xl font-bold">Products & Manufacturers</h1><p className="mt-1 text-sm text-gray-500">Map branded products and package sizes to canonical inputs, then approve them per project.</p>
 {error&&<p className="mt-4 rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p className="mt-4 rounded bg-green-50 p-3 text-sm text-green-700">{notice}</p>}
 <div className="mt-6 grid gap-5 xl:grid-cols-3">
  <Panel title="New manufacturer"><Field label="Code" value={mfg.code} set={v=>setMfg({...mfg,code:v})}/><Field label="Name" value={mfg.canonical_name} set={v=>setMfg({...mfg,canonical_name:v})}/><Field label="Short name" value={mfg.short_name} set={v=>setMfg({...mfg,short_name:v})}/><button disabled={busy||!mfg.code||!mfg.canonical_name} onClick={createMfg} className="mt-3 rounded bg-gray-900 px-4 py-2 text-sm text-white disabled:opacity-50">Create manufacturer</button></Panel>
  <Panel title="New branded product"><Field label="Product code" value={product.code} set={v=>setProduct({...product,code:v})}/><Field label="Canonical input code" value={product.canonical_input_code} set={v=>setProduct({...product,canonical_input_code:v})}/><label className="text-xs text-gray-500">Manufacturer<select value={product.manufacturer_code} onChange={e=>setProduct({...product,manufacturer_code:e.target.value})} className="mt-1 w-full rounded border p-2 text-sm"><option value="">Select</option>{manufacturers.map(x=><option key={x.code}>{x.code}</option>)}</select></label><Field label="Brand name" value={product.brand_name} set={v=>setProduct({...product,brand_name:v})}/><Field label="Composition" value={product.composition} set={v=>setProduct({...product,composition:v})}/><Field label="Registration number" value={product.registration_number} set={v=>setProduct({...product,registration_number:v})}/><div className="grid grid-cols-2 gap-2"><Field label="SKU" value={product.sku} set={v=>setProduct({...product,sku:v})}/><Field label="Pack label" value={product.pack_label} set={v=>setProduct({...product,pack_label:v})}/><Field label="Quantity" value={product.quantity} set={v=>setProduct({...product,quantity:v})}/><Field label="Unit" value={product.unit} set={v=>setProduct({...product,unit:v})}/></div><button disabled={busy||!product.code||!product.manufacturer_code||!product.sku} onClick={createProduct} className="mt-3 rounded bg-gray-900 px-4 py-2 text-sm text-white disabled:opacity-50">Create product</button></Panel>
  <Panel title="Project approval"><Field label="Project ID" value={approval.project_id} set={v=>setApproval({...approval,project_id:v})}/><label className="text-xs text-gray-500">Product<select value={approval.product_code} onChange={e=>setApproval({...approval,product_code:e.target.value})} className="mt-1 w-full rounded border p-2 text-sm"><option value="">Select</option>{products.filter(x=>x.status==="ACTIVE").map(x=><option key={x.code}>{x.code}</option>)}</select></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={approval.enabled} onChange={e=>setApproval({...approval,enabled:e.target.checked})}/>Enabled</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={approval.preferred} onChange={e=>setApproval({...approval,preferred:e.target.checked})}/>Preferred</label><Field label="Display order" value={approval.display_order} set={v=>setApproval({...approval,display_order:v})}/><Field label="Reason" value={approval.reason} set={v=>setApproval({...approval,reason:v})}/><button disabled={busy||!approval.project_id||!approval.product_code} onClick={approve} className="mt-3 rounded bg-green-700 px-4 py-2 text-sm text-white disabled:opacity-50">Save approval</button></Panel>
 </div>
 <div className="mt-6 overflow-hidden rounded bg-white shadow"><table className="w-full text-sm"><thead className="bg-gray-50"><tr>{["Code","Brand","Canonical input","Manufacturer","Packages","Registration","Status"].map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody className="divide-y">{products.map(x=><tr key={x.code}><td className="p-3 font-mono text-xs">{x.code}</td><td className="p-3 font-medium">{x.brand_name}</td><td className="p-3">{x.canonical_input_code}</td><td className="p-3">{x.manufacturer_name}</td><td className="p-3">{x.packages.map(p=>p.pack_label).join(", ")}</td><td className="p-3">{x.registration_number||"-"}</td><td className="p-3"><button onClick={async()=>{await productCatalogApi.updateProduct(x.code,{status:x.status==="ACTIVE"?"DISCONTINUED":"ACTIVE",reason:"Admin status change"});await load()}} className="rounded border px-2 py-1 text-xs">{x.status}</button></td></tr>)}</tbody></table></div>
 </div>
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="space-y-3 rounded bg-white p-5 shadow"><h2 className="font-semibold">{title}</h2>{children}</div>}
function Field({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="block text-xs text-gray-500">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded border p-2 text-sm text-gray-900"/></label>}