"""Pure DigiPin encoder/decoder utility.

Ported from the official India Post DIGIPIN JavaScript reference:
https://github.com/INDIAPOST-gov/digipin

DigiPin is deterministic from latitude/longitude. It should be generated by
backend services from captured GPS/centroid coordinates and stored on the
entity that owns the location, not preloaded for all PIN codes.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal, InvalidOperation
import re


ALGORITHM_VERSION = "INDIAPOST_DIGIPIN_2026_05_04"

DIGIPIN_GRID = [
    ["F", "C", "9", "8"],
    ["J", "3", "2", "7"],
    ["K", "4", "5", "6"],
    ["L", "M", "P", "T"],
]

MIN_LAT = Decimal("2.5")
MAX_LAT = Decimal("38.5")
MIN_LON = Decimal("63.5")
MAX_LON = Decimal("99.5")

DIGIPIN_RE = re.compile(r"^[23456789CJKLMPFT]{10}$")


@dataclass(frozen=True)
class DigiPinDecodeResult:
    latitude: Decimal
    longitude: Decimal
    algorithm_version: str = ALGORITHM_VERSION


def _decimal(value) -> Decimal:
    try:
        return Decimal(str(value))
    except (InvalidOperation, ValueError):
        raise ValueError("Latitude/longitude must be numeric")


def is_within_digipin_bounds(latitude, longitude) -> bool:
    lat = _decimal(latitude)
    lon = _decimal(longitude)
    return MIN_LAT <= lat <= MAX_LAT and MIN_LON <= lon <= MAX_LON


def normalize_digipin(value: str) -> str:
    if not isinstance(value, str):
        raise ValueError("DigiPin must be a string")
    normalized = value.strip().upper().replace(" ", "")
    if not DIGIPIN_RE.match(normalized):
        raise ValueError("Invalid DigiPin. Use the continuous 10-character India Post DigiPin code.")
    return normalized


def encode_digipin(latitude, longitude) -> str:
    lat = _decimal(latitude)
    lon = _decimal(longitude)

    if not is_within_digipin_bounds(lat, lon):
        raise ValueError("Coordinates are outside the DigiPin-supported India bounding box")

    min_lat = MIN_LAT
    max_lat = MAX_LAT
    min_lon = MIN_LON
    max_lon = MAX_LON
    code = []

    for _ in range(10):
        lat_div = (max_lat - min_lat) / Decimal("4")
        lon_div = (max_lon - min_lon) / Decimal("4")

        row = 3 - int((lat - min_lat) / lat_div)
        col = int((lon - min_lon) / lon_div)
        row = max(0, min(row, 3))
        col = max(0, min(col, 3))

        code.append(DIGIPIN_GRID[row][col])

        max_lat = min_lat + lat_div * Decimal(4 - row)
        min_lat = min_lat + lat_div * Decimal(3 - row)
        min_lon = min_lon + lon_div * Decimal(col)
        max_lon = min_lon + lon_div

    return "".join(code).upper()


def decode_digipin(value: str) -> DigiPinDecodeResult:
    code = normalize_digipin(value)

    min_lat = MIN_LAT
    max_lat = MAX_LAT
    min_lon = MIN_LON
    max_lon = MAX_LON

    for char in code:
        found = None
        for row_index, row in enumerate(DIGIPIN_GRID):
            for col_index, candidate in enumerate(row):
                if candidate == char:
                    found = (row_index, col_index)
                    break
            if found:
                break
        if not found:
            raise ValueError("Invalid DigiPin character")

        row_index, col_index = found
        lat_div = (max_lat - min_lat) / Decimal("4")
        lon_div = (max_lon - min_lon) / Decimal("4")

        lat_1 = max_lat - lat_div * Decimal(row_index + 1)
        lat_2 = max_lat - lat_div * Decimal(row_index)
        lon_1 = min_lon + lon_div * Decimal(col_index)
        lon_2 = min_lon + lon_div * Decimal(col_index + 1)

        min_lat = lat_1
        max_lat = lat_2
        min_lon = lon_1
        max_lon = lon_2

    return DigiPinDecodeResult(
        latitude=((min_lat + max_lat) / Decimal("2")).quantize(Decimal("0.000001")),
        longitude=((min_lon + max_lon) / Decimal("2")).quantize(Decimal("0.000001")),
    )


def validate_digipin(value: str) -> bool:
    try:
        normalize_digipin(value)
        return True
    except ValueError:
        return False


def generate_location_digipin(latitude, longitude) -> dict:
    return {
        "digipin": encode_digipin(latitude, longitude),
        "algorithm_version": ALGORITHM_VERSION,
    }
